// Generated by CoffeeScript 1.6.3
(function() {
  var assert, index;

  index = require('../index.js');

  assert = require('assert');

  it('should be able to run os info', function(done) {
    return index.osinfo(function(e, r) {
      console.log(r);
      assert(r["OS Type"]);
      return done();
    });
  });

}).call(this);

/*
//@ sourceMappingURL=test.map
*/
